version: '3.8'

services:
  api:
    build: ./
    container_name: mso_kleinanzeigen_api_container
    ports:
      - 8080:8080
    restart: unless-stopped
    env_file:
      - ./config/.env
    networks:
      mso_kleinanzeigen:
        ipv4_address: 10.20.100.10
    depends_on:
      - db

  db:
    image: mongo:latest
    networks:
      mso_kleinanzeigen:
        ipv4_address: 10.20.100.20
    ports:
      - 27017:27017
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ./mongosave:/data/db

networks:
  mso_kleinanzeigen:
    external:
      name: mso_rooms
      
